#security:
# enabled: false
#----------------------------
# Spring Boot configuration
#----------------------------
spring:
  hateoas:
    use-hal-as-default-json-media-type: false
    jackson:
      default-property-inclusion: NON_ABSENT
    #security:
    # ignored: /**
  main:
    banner-mode: "off"
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/basket
    username: postgres
    password: J1cpt@adm
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
      # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
#----------------------------
# Server configuration
#----------------------------
server:
  port: 8080 #set your port